# permissions for end users to view coffees.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coffee-viewer-role
rules:
- apiGroups:
  - beverage.coffee.demo.purestorage.com
  resources:
  - coffees
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - beverage.coffee.demo.purestorage.com
  resources:
  - coffees/status
  verbs:
  - get
